[plugin]
enabled = false
config_version = "0.1.0"

[telegram_bot]
token = ""
api_base = "https://api.telegram.org"
poll_timeout = 20
proxy_enabled = false
proxy_url = ""
proxy_from_env = false

[chat]
group_list_type = "whitelist"
group_list = []
private_list_type = "whitelist"
private_list = []
ban_user_id = []
